# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wdV6XbGeDYmuYHC9p7ep1CNErEo4gsIi
"""

import pandas as pd

df=pd.read_csv("https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/2014-15_To_2016-17_School-_Level_NYC_Regents_Report_For_All_Variables.csv")

df

df.describe()

df.shape

df.head(8)

df2=df.head(8)

df3=df[df["School Name"]=="P.S. 034 Franklin D. Roosevelt"]

df4=df3[["School Name","Regents Exam","Percent Scoring Below 65","Percent Scoring 65 or Above","Percent Scoring 80 or Above"]]

df4

df_living=df4[df4["Regents Exam"]=="Living Environment"]

"""df_living['Percent Scoring 65 or Above'].mean"""

df_living['Percent Scoring 65 or Above'].mean

df_living_mean=df_living['Percent Scoring 65 or Above'].mean



df=df

df1=df[["School Name","Regents Exam","Percent Scoring Below 65","Percent Scoring 65 or Above","Percent Scoring 80 or Above"]].head(8)

df1["School Name"]